// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.camiloporto.tenant.model;

import br.com.camiloporto.tenant.model.Imovel;
import java.io.Serializable;

privileged aspect Imovel_Roo_Serializable {
    
    declare parents: Imovel implements Serializable;
    
    private static final long Imovel.serialVersionUID = 1L;
    
}
