// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.camiloporto.tenant.model;

import br.com.camiloporto.tenant.model.ImovelMedia;
import java.io.Serializable;

privileged aspect ImovelMedia_Roo_Serializable {
    
    declare parents: ImovelMedia implements Serializable;
    
    private static final long ImovelMedia.serialVersionUID = 1L;
    
}
