// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.camiloporto.tenant.model;

import br.com.camiloporto.tenant.model.Usuario;
import java.io.Serializable;

privileged aspect Usuario_Roo_Serializable {
    
    declare parents: Usuario implements Serializable;
    
    private static final long Usuario.serialVersionUID = 1L;
    
}
